package test
import java.util.List;

rule "rule1"
    salience 2
    when
        $customer:Customer(name == "张三" , age == 20)
    then
        System.out.println("modify before customer: "+$customer.getName()+" "+$customer.getAge());
        modify($customer){
            setName("李四"),
            setAge(12)
        }
    end

rule "rule2"
    salience 1
    when
        $customer:Customer(name == "李四")
    then
        System.out.println("modify after customer: "+$customer.getName()+" "+$customer.getAge());
    end
