package test;
import java.util.List;


rule "rule1"
    salience 2
    when
        eval(true)
    then
         Customer customer = new Customer();
         customer.setName("zhangsan");
         customer.setAge(1);
         insert(customer);
         System.out.println("rule 1: insert "+customer);
     end

rule "rule2"
    salience 1
    when
        $customer:Customer(name == "zhangsan")
    then
//        retract($customer)
        System.out.println("rule 2: remove "+$customer);
    end

query "query fact count"
    Customer()
end
