package test;

declare Address
    city: String
    addressName: String
end

rule "rule0"
    no-loop true
    when
        $addr:Address(city == "Shanghai")
    then
        System.out.println("addressName: "+$addr.getAddressName());
end

rule "rule1"
    no-loop true
    when
    then
        # 使用定义的Fact对象，并利用insert操作符将其插入到当前的WorkingMemory当中
        Address address = new Address();
        address.setCity("Guangzhou");
        address.setAddressName("DongFeng Road");
        insert(address);
        System.out.println("set an address");
end

rule "rule2"
   when
        $address:Address(city == "Guangzhou")
   then
        System.out.println("addressName: "+$address.getAddressName());
end


