package test
import java.util.List;

rule "rule1"
//salience 4
    when
        $customer:Customer(name matches "li.*")
    then
        System.out.println("rule1: "+$customer.getName());
    end

 rule "rule2"
//    salience 3
    when
        eval(true)
    then
        Customer cus = new Customer("jj");
        insert(cus);
        System.out.println("rule 2: "+  " insert jj");
    end

rule "rule3"
//    salience 2
    when
        $obj:Customer(name == "jj")
    then
        System.out.println("rule 3 : "+$obj.getName());
        $obj.setName("fuxk");
        update($obj);
     end

rule "rule4"
    when
        $obj:Customer(name == "fuxk" && age< 10);
    then
        $obj.setAge($obj.getAge() + 1);
        System.out.println("rule 4: "+$obj.getName());
        update($obj);
    end

rule "rule5"
    salience 1
    when
       $customer:Customer(age < 10)
    then
        System.out.println("rule 5: "+$customer.getName()+" "+$customer.getAge());
    end

query "query fact count"
    Customer();
end