package sample
import sample.Employ

rule"Total"
  ruleflow-group"sum_salary"
when
   emp: Employ()
then
   try {
Thread.sleep(1000);} catch (InterruptedException e) {
    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
}
   System.out.println(Thread.currentThread()+ " : execrule Total ... ");
   double total =emp.getBasicSalary() + emp.getDutySalary() +
                 emp.getBonus();
   emp.setTotalSalary(total*emp.getPercent());
end